### PR TITLE
Resolves #25: [FEATURE] Adding Scroll Animation

### LINKED ISSUE #25: feat: adding scroll animation
Hey! 
I want to add the scroll animation to this beautiful website. It will enhance the user experience for sure.
Please assign this issue to me.

### PR DESCRIPTION
**Pull request by superiorsd10**
Resolves #25 
I've added the scroll animation using the `Animate On Scroll` library. Please review it.

### CODE REVIEW

**Comment by Sidd2024** [comment]
@superiorsd10 awesome work!💙, merged.

**Comment by Sidd2024** [comment]
don't forget to 🌟 this repo...

**Comment by superiorsd10** [comment]
> @superiorsd10 awesome work!💙, merged.

Thank you :) Happy Hactoberfest!

**Comment by Sidd2024** [comment]
same 2 u brother...

**Pull request merged**
